Vagrant.configure( "2" ) do |config|
    config.vm.define( "influxdb" ) do |vm|
        vm.vm.provider( "docker" ) do |d|
            d.image = "mtinside/influxdb-test"
            d.ports = [ "8083:8083", "8086:8086" ]
        end
    end
end
